"""Markdown reporter — writes pipeline results to markdown files."""

import os
from datetime import datetime
from pathlib import Path


def write_report(result: dict, output_dir: str | None = None) -> Path:
    """Write pipeline result as a markdown report."""
    if output_dir is None:
        data_dir = os.getenv("GITREPO_AGENT_DATA_DIR", "/tmp/gitrepo-agent")
        output_dir = os.path.join(data_dir, "data", "reports")

    os.makedirs(output_dir, exist_ok=True)
    date = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date}_{result['pipeline']}_report.md"
    path = Path(output_dir) / filename

    lines = [
        f"# Pipeline Report: {result['pipeline']}",
        f"**Date:** {datetime.now().isoformat()}",
        f"**Result:** {'PASSED' if result['passed'] else 'FAILED'}",
        "",
        "## Steps",
        "",
    ]

    for step in result.get("steps", []):
        icon_map = {"passed": "\u2705", "failed": "\u274c"}
        icon = icon_map.get(step["status"], "\u23ed\ufe0f")
        duration = step.get('duration_ms', 0)
        lines.append(f"### {icon} {step['name']} \u2014 {step['status']} ({duration}ms)")
        lines.append("")

        for finding in step.get("findings", []):
            sev_icons = {"error": "\U0001f534", "warning": "\U0001f7e1", "info": "\U0001f535"}
            sev = sev_icons.get(finding["severity"], "\u26aa")
            lines.append(f"- {sev} {finding['message']}")

        lines.append("")

    lines.append("---")
    lines.append("*Generated by GitRepo Agent Pipeline Runner*")

    path.write_text("\n".join(lines))
    return path
