defmodule GitrepoAgent.PrEvaluator do
  @moduledoc """
  Evaluates Pull Requests using the 5-category weighted scoring system.

  Categories and weights:
  - Security: 25%
  - Design: 25%
  - Practices: 20%
  - Style: 15%
  - Documentation: 15%

  See spec/SCORING.md for full details.
  """

  @weights %{
    security: 0.25,
    design: 0.25,
    practices: 0.20,
    style: 0.15,
    documentation: 0.15
  }

  @verdict_thresholds [
    {90, :approve},
    {70, :approve_with_comments},
    {50, :request_changes},
    {0, :reject}
  ]

  defstruct [:pr_id, :repo, :scores, :verdict, :findings, :ai_assisted]

  @doc "Calculate weighted score from category scores"
  def calculate_score(category_scores) do
    Enum.reduce(@weights, 0.0, fn {category, weight}, acc ->
      score = Map.get(category_scores, category, 0)
      acc + score * weight
    end)
    |> Float.round(1)
  end

  @doc "Determine verdict from overall score"
  def verdict(score) do
    Enum.find_value(@verdict_thresholds, :reject, fn {threshold, verdict} ->
      if score >= threshold, do: verdict
    end)
  end

  @doc "Detect if commits contain AI-assisted patterns"
  def detect_ai_assisted(commit_messages) do
    patterns = [
      ~r/Co-Authored-By:.*claude/i,
      ~r/Co-Authored-By:.*copilot/i,
      ~r/Co-Authored-By:.*\bAI\b/i,
      ~r/Generated by/i,
      ~r/🤖/,
      ~r/\[bot\]/i,
      ~r/aider/i,
      ~r/cursor/i
    ]

    Enum.any?(commit_messages, fn msg ->
      Enum.any?(patterns, &Regex.match?(&1, msg))
    end)
  end
end
