defmodule GitrepoAgent.ReportGenerator do
  @moduledoc """
  Generates weekly reports and delivers them to the Librarian
  agent's input folder and broadcasts summaries via IAMQ.
  """
  use GenServer

  def start_link(_opts) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  @impl true
  def init(state) do
    {:ok, state}
  end

  @doc "Generate weekly report for all watched repos"
  def generate_weekly do
    GenServer.call(__MODULE__, :generate_weekly, :infinity)
  end

  @impl true
  def handle_call(:generate_weekly, _from, state) do
    report = build_weekly_report()
    deliver_report(report)
    {:reply, :ok, state}
  end

  defp build_weekly_report do
    date = Date.utc_today() |> Date.to_iso8601()
    repos = load_repos()

    sections = Enum.map(repos, fn repo ->
      repo_path = GitrepoAgent.RepoManager.repo_path(repo["vcs"], repo["org"], repo["project"])
      commits = GitrepoAgent.StatsCollector.collect_commits(repo_path)
      authors = GitrepoAgent.StatsCollector.author_stats(commits)
      scoring = GitrepoAgent.Scoring.load(repo["name"])

      """
      ## #{repo["name"]}

      **Commits this week:** #{length(commits)}
      **Active authors:** #{length(authors)}
      **AI-assisted commits:** #{Enum.count(commits, & &1.ai_assisted)}

      ### Author Activity

      | Author | Commits | AI-Assisted | Avg Score |
      |--------|---------|-------------|-----------|
      #{format_author_table(authors, repo["name"])}

      ### Flagged PRs

      #{format_flagged_prs(scoring)}
      """
    end)

    """
    # Weekly GitRepo Report — #{date}

    #{Enum.join(sections, "\n---\n\n")}

    ---
    *Generated by GitRepo Agent*
    """
  end

  defp format_author_table(authors, repo_name) do
    Enum.map_join(authors, "\n", fn a ->
      avg = GitrepoAgent.Scoring.author_average(repo_name, a.author)
      avg_str = if avg, do: "#{avg}", else: "—"
      "| #{a.author} | #{a.commit_count} | #{a.ai_assisted} | #{avg_str} |"
    end)
  end

  defp format_flagged_prs(scoring) do
    scoring
    |> Map.get("prs", %{})
    |> Enum.filter(fn {_id, pr} -> (pr["score"] || 100) < 50 end)
    |> case do
      [] -> "_No flagged PRs this period._"
      prs ->
        Enum.map_join(prs, "\n", fn {id, pr} ->
          "- **PR ##{id}**: score #{pr["score"]}, verdict: #{pr["verdict"]}"
        end)
    end
  end

  defp deliver_report(report) do
    date = Date.utc_today() |> Date.to_iso8601()

    # Save to data dir
    data_dir = System.get_env("GITREPO_AGENT_DATA_DIR", "/tmp/gitrepo-agent")
    report_path = Path.join([data_dir, "data", "reports", "#{date}_weekly_report.md"])
    File.mkdir_p!(Path.dirname(report_path))
    File.write!(report_path, report)

    # Deliver to librarian
    librarian_dir = System.get_env("LIBRARIAN_DATA_FOLDER", "")
    unless librarian_dir == "" do
      librarian_path = Path.join([Path.expand(librarian_dir), "input", "#{date}_weekly_report.md"])
      File.mkdir_p!(Path.dirname(librarian_path))
      File.write!(librarian_path, report)
    end
  end

  defp load_repos do
    config_path = Path.join(File.cwd!(), "config/repos.json")
    case File.read(config_path) do
      {:ok, content} -> Jason.decode!(content) |> Map.get("repos", [])
      {:error, _} -> []
    end
  end
end
